// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdenesDeinversion.Models.Entity;

#nullable disable

namespace OrdenesDeinversion.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250119223913_Segunda")]
    partial class Segunda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrdenesDeinversion.Models.Entity.Dominio.Activos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("float");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<int>("TipoActivo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("activos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Apple",
                            PrecioUnitario = 177.97,
                            Ticker = "AAPL",
                            TipoActivo = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Alphabet Inc",
                            PrecioUnitario = 138.21000000000001,
                            Ticker = "GOOGL",
                            TipoActivo = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Microsoft",
                            PrecioUnitario = 329.04000000000002,
                            Ticker = "MSFT",
                            TipoActivo = 1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Coca Cola",
                            PrecioUnitario = 58.299999999999997,
                            Ticker = "KO",
                            TipoActivo = 1
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Walmart",
                            PrecioUnitario = 163.41999999999999,
                            Ticker = "WMT",
                            TipoActivo = 1
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "BONOS ARGENTINA USD 2030 L.A",
                            PrecioUnitario = 307.39999999999998,
                            Ticker = "AL30",
                            TipoActivo = 2
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Bonos Globales Argentina USD Step Up 2030",
                            PrecioUnitario = 336.10000000000002,
                            Ticker = "GD30",
                            TipoActivo = 2
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Delta Pesos Clase A",
                            PrecioUnitario = 0.018100000000000002,
                            Ticker = "Delta.Pesos",
                            TipoActivo = 3
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Fima Premium Clase A",
                            PrecioUnitario = 0.031699999999999999,
                            Ticker = "Fima.Premium",
                            TipoActivo = 3
                        });
                });

            modelBuilder.Entity("OrdenesDeinversion.Models.Entity.Dominio.OrdenesDeInversion", b =>
                {
                    b.Property<int>("IdDeLaOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDeLaOrden"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("IdDeLaCuenta")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreDelActivo")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdDeLaOrden");

                    b.ToTable("ordenesDeInversion");
                });
#pragma warning restore 612, 618
        }
    }
}
